Changed program Structure
r-stha/C-calculator pull request #2
Opened 2024-11-30 08:27 UTC by r-stha

Made a new file for each class.
Made a new file and class for accepting choices from a option.

2024-12-02 15:39 UTC, hstha requested changes

2024-12-02 15:39 UTC, hstha commented on ArthmeticCalculation.cs
> +        double Base = Convert.ToDouble(Console.ReadLine());
variable name never start with uppercase

2024-12-02 15:39 UTC, hstha commented on ArthmeticCalculation.cs
> +        var (operand1, operand2) = Input.TakeArthmeticInput();
Since you are learning, never use var, be specific on which datatype are you using

2024-12-02 15:39 UTC, hstha commented on ArthmeticCalculation.cs
> +        if (operand2 == 0)
Better use try catch instead of checking operand2 == 0

2024-12-02 15:39 UTC, hstha commented on ArthmeticCalculation.cs
> +    public static double FactorialRecursion(double number)
FactorialRecursion is redundant, you can simply name is Factoral

2024-12-02 15:39 UTC, hstha commented on ArthmeticCalculation.cs
> +    public static double PowerRecursion(double baseNumber, double powerNumber)
Please use proper naming, what does PowerRecurssion mean?

2024-12-02 15:39 UTC, hstha commented on Menu.cs
> +2. Subtraction
Use proper formating

2024-12-02 15:39 UTC, hstha commented on Menu.cs
> +2. Find combination and permutation
Use proper formating

2024-12-02 15:39 UTC, hstha commented on Menu.cs
> +        Console.WriteLine(@"1. Degree
Use proper formating

2024-12-02 15:39 UTC, hstha commented on Menu.cs
> +        Console.WriteLine(@"1. Binary to decimal
Use proper formating

2024-12-02 15:39 UTC, hstha commented on OptionChoose.cs
> +        if (userChoice == 1)
If you are clearing console in both cases than you can take it out them to top

2024-12-03 11:10 UTC, r-stha commented
changed variable name which starts with Uppercase
Added specific data types instead of using var
Added try catch instead of checking operand
Gave a meaning name to factorial and power calculation
Properly formatted the menu section
Cleared the console for the top

2024-12-07 05:10 UTC, r-stha commented on ArthmeticCalculation.cs
> +        double Base = Convert.ToDouble(Console.ReadLine());
named as radix

2024-12-07 05:10 UTC, r-stha commented on ArthmeticCalculation.cs
> +        var (operand1, operand2) = Input.TakeArthmeticInput();
given datatype of double to both variable

2024-12-07 05:11 UTC, r-stha commented on ArthmeticCalculation.cs
> +        if (operand2 == 0)
Used DivisionByZeroException in try catch

2024-12-07 05:12 UTC, r-stha commented on ArthmeticCalculation.cs
> +    public static double FactorialRecursion(double number)
Given the name of factoral

2024-12-21 14:28 UTC, merged